// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxqbGroR5yNhAW0j-OGysU3Ww1P5ddoq4',
    appId: '1:136672532812:web:56a2c434bc94f093c857e9',
    messagingSenderId: '136672532812',
    projectId: 'calendar-service-79804',
    authDomain: 'calendar-service-79804.firebaseapp.com',
    storageBucket: 'calendar-service-79804.firebasestorage.app',
    measurementId: 'G-DTYKXNKJK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxQqB6dXIMgqE97dcq4UMKLVYUtj7MLr0',
    appId: '1:136672532812:android:efeb949ea7be89a4c857e9',
    messagingSenderId: '136672532812',
    projectId: 'calendar-service-79804',
    storageBucket: 'calendar-service-79804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjU-AUJZaH5BwV9R8JOLkCF-F8UK6Dx5k',
    appId: '1:136672532812:ios:b456e046b1786e75c857e9',
    messagingSenderId: '136672532812',
    projectId: 'calendar-service-79804',
    storageBucket: 'calendar-service-79804.firebasestorage.app',
    iosBundleId: 'com.example.calander',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjU-AUJZaH5BwV9R8JOLkCF-F8UK6Dx5k',
    appId: '1:136672532812:ios:b456e046b1786e75c857e9',
    messagingSenderId: '136672532812',
    projectId: 'calendar-service-79804',
    storageBucket: 'calendar-service-79804.firebasestorage.app',
    iosBundleId: 'com.example.calander',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxqbGroR5yNhAW0j-OGysU3Ww1P5ddoq4',
    appId: '1:136672532812:web:5a95eaa264de7fc9c857e9',
    messagingSenderId: '136672532812',
    projectId: 'calendar-service-79804',
    authDomain: 'calendar-service-79804.firebaseapp.com',
    storageBucket: 'calendar-service-79804.firebasestorage.app',
    measurementId: 'G-G1BJRMPZMS',
  );
}
